server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: location-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/location/*
          filters:
            - name: CircuitBreaker
              args:
                name: location-service
                fallbackUri: forward:/fallback
  security:
    oauth2:
      resource-server:
        opaque-token:
          client-secret:  IsIZ1bwUY8LKQBpTNTwnzMTc9woXDEie
          client-id: tom-gateway-client
          introspection-uri: http://localhost:8888/auth/realms/My-Realm/protocol/openid-connect/token/introspect