server:
  port: 9292

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          clone-on-start: true
  profiles:
    active: dev